export type KeyboardLayout = 
  | 'QWERTY' 
  | 'AZERTY' 
  | 'QWERTZ' 
  | 'Swiss' 
  | 'Nordic (SE/FI)' 
  | 'Nordic (NO/DK)' 
  | 'Spanish' 
  | 'Portuguese' 
  | 'Italian' 
  | 'Turkish' 
  | 'DVORAK' 
  | 'Colemak';

export interface KeyLabelMap {
  [code: string]: {
    label: string;
    subLabel?: string;
  };
}

export const LAYOUT_DEFINITIONS: Record<KeyboardLayout, KeyLabelMap> = {
  // 1. QWERTY (US Standard)
  'QWERTY': {
    'Backquote': { label: '`', subLabel: '~' },
    'Digit1': { label: '1', subLabel: '!' },
    'Digit2': { label: '2', subLabel: '@' },
    'Digit3': { label: '3', subLabel: '#' },
    'Digit4': { label: '4', subLabel: '$' },
    'Digit5': { label: '5', subLabel: '%' },
    'Digit6': { label: '6', subLabel: '^' },
    'Digit7': { label: '7', subLabel: '&' },
    'Digit8': { label: '8', subLabel: '*' },
    'Digit9': { label: '9', subLabel: '(' },
    'Digit0': { label: '0', subLabel: ')' },
    'Minus': { label: '-', subLabel: '_' },
    'Equal': { label: '=', subLabel: '+' },
    'KeyQ': { label: 'Q' },
    'KeyW': { label: 'W' },
    'KeyE': { label: 'E' },
    'KeyR': { label: 'R' },
    'KeyT': { label: 'T' },
    'KeyY': { label: 'Y' },
    'KeyU': { label: 'U' },
    'KeyI': { label: 'I' },
    'KeyO': { label: 'O' },
    'KeyP': { label: 'P' },
    'BracketLeft': { label: '[', subLabel: '{' },
    'BracketRight': { label: ']', subLabel: '}' },
    'Backslash': { label: '\\', subLabel: '|' },
    'KeyA': { label: 'A' },
    'KeyS': { label: 'S' },
    'KeyD': { label: 'D' },
    'KeyF': { label: 'F' },
    'KeyG': { label: 'G' },
    'KeyH': { label: 'H' },
    'KeyJ': { label: 'J' },
    'KeyK': { label: 'K' },
    'KeyL': { label: 'L' },
    'Semicolon': { label: ';', subLabel: ':' },
    'Quote': { label: '\'', subLabel: '"' },
    'KeyZ': { label: 'Z' },
    'KeyX': { label: 'X' },
    'KeyC': { label: 'C' },
    'KeyV': { label: 'V' },
    'KeyB': { label: 'B' },
    'KeyN': { label: 'N' },
    'KeyM': { label: 'M' },
    'Comma': { label: ',', subLabel: '<' },
    'Period': { label: '.', subLabel: '>' },
    'Slash': { label: '/', subLabel: '?' }
  },

  // 2. AZERTY (French)
  'AZERTY': {
    'Backquote': { label: '²', subLabel: '' },
    'Digit1': { label: '&', subLabel: '1' },
    'Digit2': { label: 'é', subLabel: '2' },
    'Digit3': { label: '"', subLabel: '3' },
    'Digit4': { label: '\'', subLabel: '4' },
    'Digit5': { label: '(', subLabel: '5' },
    'Digit6': { label: '-', subLabel: '6' },
    'Digit7': { label: 'è', subLabel: '7' },
    'Digit8': { label: '_', subLabel: '8' },
    'Digit9': { label: 'ç', subLabel: '9' },
    'Digit0': { label: 'à', subLabel: '0' },
    'Minus': { label: ')', subLabel: '°' },
    'Equal': { label: '=', subLabel: '+' },
    'KeyQ': { label: 'A' },
    'KeyW': { label: 'Z' },
    'KeyE': { label: 'E' },
    'KeyR': { label: 'R' },
    'KeyT': { label: 'T' },
    'KeyY': { label: 'Y' },
    'KeyU': { label: 'U' },
    'KeyI': { label: 'I' },
    'KeyO': { label: 'O' },
    'KeyP': { label: 'P' },
    'BracketLeft': { label: '^', subLabel: '¨' },
    'BracketRight': { label: '$', subLabel: '£' },
    'Backslash': { label: '*', subLabel: 'µ' },
    'KeyA': { label: 'Q' },
    'KeyS': { label: 'S' },
    'KeyD': { label: 'D' },
    'KeyF': { label: 'F' },
    'KeyG': { label: 'G' },
    'KeyH': { label: 'H' },
    'KeyJ': { label: 'J' },
    'KeyK': { label: 'K' },
    'KeyL': { label: 'L' },
    'Semicolon': { label: 'M', subLabel: '' },
    'Quote': { label: 'ù', subLabel: '%' },
    'KeyZ': { label: 'W' },
    'KeyX': { label: 'X' },
    'KeyC': { label: 'C' },
    'KeyV': { label: 'V' },
    'KeyB': { label: 'B' },
    'KeyN': { label: 'N' },
    'KeyM': { label: ',', subLabel: '?' },
    'Comma': { label: ';', subLabel: '.' },
    'Period': { label: ':', subLabel: '/' },
    'Slash': { label: '!', subLabel: '§' }
  },

  // 3. QWERTZ (German)
  'QWERTZ': {
    'Backquote': { label: '^', subLabel: '°' },
    'Digit1': { label: '1', subLabel: '!' },
    'Digit2': { label: '2', subLabel: '"' },
    'Digit3': { label: '3', subLabel: '§' },
    'Digit4': { label: '4', subLabel: '$' },
    'Digit5': { label: '5', subLabel: '%' },
    'Digit6': { label: '6', subLabel: '&' },
    'Digit7': { label: '7', subLabel: '/' },
    'Digit8': { label: '8', subLabel: '(' },
    'Digit9': { label: '9', subLabel: ')' },
    'Digit0': { label: '0', subLabel: '=' },
    'Minus': { label: 'ß', subLabel: '?' },
    'Equal': { label: '´', subLabel: '`' },
    'KeyQ': { label: 'Q' },
    'KeyW': { label: 'W' },
    'KeyE': { label: 'E' },
    'KeyR': { label: 'R' },
    'KeyT': { label: 'T' },
    'KeyY': { label: 'Z' }, // Swapped Y and Z
    'KeyU': { label: 'U' },
    'KeyI': { label: 'I' },
    'KeyO': { label: 'O' },
    'KeyP': { label: 'P' },
    'BracketLeft': { label: 'Ü', subLabel: '' },
    'BracketRight': { label: '+', subLabel: '*' },
    'Backslash': { label: '#', subLabel: '\'' },
    'KeyA': { label: 'A' },
    'KeyS': { label: 'S' },
    'KeyD': { label: 'D' },
    'KeyF': { label: 'F' },
    'KeyG': { label: 'G' },
    'KeyH': { label: 'H' },
    'KeyJ': { label: 'J' },
    'KeyK': { label: 'K' },
    'KeyL': { label: 'L' },
    'Semicolon': { label: 'Ö', subLabel: '' },
    'Quote': { label: 'Ä', subLabel: '' },
    'KeyZ': { label: 'Y' }, // Swapped Z and Y
    'KeyX': { label: 'X' },
    'KeyC': { label: 'C' },
    'KeyV': { label: 'V' },
    'KeyB': { label: 'B' },
    'KeyN': { label: 'N' },
    'KeyM': { label: 'M' },
    'Comma': { label: ',', subLabel: ';' },
    'Period': { label: '.', subLabel: ':' },
    'Slash': { label: '-', subLabel: '_' }
  },

  // 4. Swiss (Swiss French / German QWERTZ)
  'Swiss': {
    'Backquote': { label: '§', subLabel: '°' },
    'Digit1': { label: '1', subLabel: '+' },
    'Digit2': { label: '2', subLabel: '"' },
    'Digit3': { label: '3', subLabel: '*' },
    'Digit4': { label: '4', subLabel: 'ç' },
    'Digit5': { label: '5', subLabel: '%' },
    'Digit6': { label: '6', subLabel: '&' },
    'Digit7': { label: '7', subLabel: '/' },
    'Digit8': { label: '8', subLabel: '(' },
    'Digit9': { label: '9', subLabel: ')' },
    'Digit0': { label: '0', subLabel: '=' },
    'Minus': { label: '\'', subLabel: '?' },
    'Equal': { label: '^', subLabel: '`' },
    'KeyQ': { label: 'Q' },
    'KeyW': { label: 'W' },
    'KeyE': { label: 'E' },
    'KeyR': { label: 'R' },
    'KeyT': { label: 'T' },
    'KeyY': { label: 'Z' },
    'KeyU': { label: 'U' },
    'KeyI': { label: 'I' },
    'KeyO': { label: 'O' },
    'KeyP': { label: 'P' },
    'BracketLeft': { label: 'è', subLabel: 'ü' },
    'BracketRight': { label: '¨', subLabel: '!' },
    'Backslash': { label: '$', subLabel: '£' },
    'KeyA': { label: 'A' },
    'KeyS': { label: 'S' },
    'KeyD': { label: 'D' },
    'KeyF': { label: 'F' },
    'KeyG': { label: 'G' },
    'KeyH': { label: 'H' },
    'KeyJ': { label: 'J' },
    'KeyK': { label: 'K' },
    'KeyL': { label: 'L' },
    'Semicolon': { label: 'é', subLabel: 'ö' },
    'Quote': { label: 'à', subLabel: 'ä' },
    'KeyZ': { label: 'Y' },
    'KeyX': { label: 'X' },
    'KeyC': { label: 'C' },
    'KeyV': { label: 'V' },
    'KeyB': { label: 'B' },
    'KeyN': { label: 'N' },
    'KeyM': { label: 'M' },
    'Comma': { label: ',', subLabel: ';' },
    'Period': { label: '.', subLabel: ':' },
    'Slash': { label: '-', subLabel: '_' }
  },

  // 5. Nordic (SE/FI - Swedish & Finnish)
  'Nordic (SE/FI)': {
    'Backquote': { label: '§', subLabel: '½' },
    'Digit1': { label: '1', subLabel: '!' },
    'Digit2': { label: '2', subLabel: '"' },
    'Digit3': { label: '3', subLabel: '#' },
    'Digit4': { label: '4', subLabel: '¤' },
    'Digit5': { label: '5', subLabel: '%' },
    'Digit6': { label: '6', subLabel: '&' },
    'Digit7': { label: '7', subLabel: '/' },
    'Digit8': { label: '8', subLabel: '(' },
    'Digit9': { label: '9', subLabel: ')' },
    'Digit0': { label: '0', subLabel: '=' },
    'Minus': { label: '+', subLabel: '?' },
    'Equal': { label: '´', subLabel: '`' },
    'KeyQ': { label: 'Q' },
    'KeyW': { label: 'W' },
    'KeyE': { label: 'E' },
    'KeyR': { label: 'R' },
    'KeyT': { label: 'T' },
    'KeyY': { label: 'Y' },
    'KeyU': { label: 'U' },
    'KeyI': { label: 'I' },
    'KeyO': { label: 'O' },
    'KeyP': { label: 'P' },
    'BracketLeft': { label: 'Å', subLabel: '' },
    'BracketRight': { label: '^', subLabel: '¨' },
    'Backslash': { label: '\'', subLabel: '*' },
    'KeyA': { label: 'A' },
    'KeyS': { label: 'S' },
    'KeyD': { label: 'D' },
    'KeyF': { label: 'F' },
    'KeyG': { label: 'G' },
    'KeyH': { label: 'H' },
    'KeyJ': { label: 'J' },
    'KeyK': { label: 'K' },
    'KeyL': { label: 'L' },
    'Semicolon': { label: 'Ö', subLabel: '' },
    'Quote': { label: 'Ä', subLabel: '' },
    'KeyZ': { label: 'Z' },
    'KeyX': { label: 'X' },
    'KeyC': { label: 'C' },
    'KeyV': { label: 'V' },
    'KeyB': { label: 'B' },
    'KeyN': { label: 'N' },
    'KeyM': { label: 'M' },
    'Comma': { label: ',', subLabel: ';' },
    'Period': { label: '.', subLabel: ':' },
    'Slash': { label: '-', subLabel: '_' }
  },

  // 6. Nordic (NO/DK - Norwegian & Danish)
  'Nordic (NO/DK)': {
    'Backquote': { label: '|', subLabel: '§' },
    'Digit1': { label: '1', subLabel: '!' },
    'Digit2': { label: '2', subLabel: '"' },
    'Digit3': { label: '3', subLabel: '#' },
    'Digit4': { label: '4', subLabel: '¤' },
    'Digit5': { label: '5', subLabel: '%' },
    'Digit6': { label: '6', subLabel: '&' },
    'Digit7': { label: '7', subLabel: '/' },
    'Digit8': { label: '8', subLabel: '(' },
    'Digit9': { label: '9', subLabel: ')' },
    'Digit0': { label: '0', subLabel: '=' },
    'Minus': { label: '+', subLabel: '?' },
    'Equal': { label: '\\', subLabel: '`' },
    'KeyQ': { label: 'Q' },
    'KeyW': { label: 'W' },
    'KeyE': { label: 'E' },
    'KeyR': { label: 'R' },
    'KeyT': { label: 'T' },
    'KeyY': { label: 'Y' },
    'KeyU': { label: 'U' },
    'KeyI': { label: 'I' },
    'KeyO': { label: 'O' },
    'KeyP': { label: 'P' },
    'BracketLeft': { label: 'Å', subLabel: '' },
    'BracketRight': { label: '^', subLabel: '¨' },
    'Backslash': { label: '\'', subLabel: '*' },
    'KeyA': { label: 'A' },
    'KeyS': { label: 'S' },
    'KeyD': { label: 'D' },
    'KeyF': { label: 'F' },
    'KeyG': { label: 'G' },
    'KeyH': { label: 'H' },
    'KeyJ': { label: 'J' },
    'KeyK': { label: 'K' },
    'KeyL': { label: 'L' },
    'Semicolon': { label: 'Ø', subLabel: 'Æ' },
    'Quote': { label: 'Æ', subLabel: 'Ø' },
    'KeyZ': { label: 'Z' },
    'KeyX': { label: 'X' },
    'KeyC': { label: 'C' },
    'KeyV': { label: 'V' },
    'KeyB': { label: 'B' },
    'KeyN': { label: 'N' },
    'KeyM': { label: 'M' },
    'Comma': { label: ',', subLabel: ';' },
    'Period': { label: '.', subLabel: ':' },
    'Slash': { label: '-', subLabel: '_' }
  },

  // 7. Spanish (Spain / LATAM)
  'Spanish': {
    'Backquote': { label: 'º', subLabel: 'ª' },
    'Digit1': { label: '1', subLabel: '!' },
    'Digit2': { label: '2', subLabel: '"' },
    'Digit3': { label: '3', subLabel: '·' },
    'Digit4': { label: '4', subLabel: '$' },
    'Digit5': { label: '5', subLabel: '%' },
    'Digit6': { label: '6', subLabel: '&' },
    'Digit7': { label: '7', subLabel: '/' },
    'Digit8': { label: '8', subLabel: '(' },
    'Digit9': { label: '9', subLabel: ')' },
    'Digit0': { label: '0', subLabel: '=' },
    'Minus': { label: '\'', subLabel: '?' },
    'Equal': { label: '¡', subLabel: '¿' },
    'KeyQ': { label: 'Q' },
    'KeyW': { label: 'W' },
    'KeyE': { label: 'E' },
    'KeyR': { label: 'R' },
    'KeyT': { label: 'T' },
    'KeyY': { label: 'Y' },
    'KeyU': { label: 'U' },
    'KeyI': { label: 'I' },
    'KeyO': { label: 'O' },
    'KeyP': { label: 'P' },
    'BracketLeft': { label: '`', subLabel: '^' },
    'BracketRight': { label: '+', subLabel: '*' },
    'Backslash': { label: 'ç', subLabel: 'Ç' },
    'KeyA': { label: 'A' },
    'KeyS': { label: 'S' },
    'KeyD': { label: 'D' },
    'KeyF': { label: 'F' },
    'KeyG': { label: 'G' },
    'KeyH': { label: 'H' },
    'KeyJ': { label: 'J' },
    'KeyK': { label: 'K' },
    'KeyL': { label: 'L' },
    'Semicolon': { label: 'Ñ', subLabel: '' },
    'Quote': { label: '´', subLabel: '¨' },
    'KeyZ': { label: 'Z' },
    'KeyX': { label: 'X' },
    'KeyC': { label: 'C' },
    'KeyV': { label: 'V' },
    'KeyB': { label: 'B' },
    'KeyN': { label: 'N' },
    'KeyM': { label: 'M' },
    'Comma': { label: ',', subLabel: ';' },
    'Period': { label: '.', subLabel: ':' },
    'Slash': { label: '-', subLabel: '_' }
  },

  // 8. Portuguese (Portugal & Brazil)
  'Portuguese': {
    'Backquote': { label: '\'', subLabel: '"' },
    'Digit1': { label: '1', subLabel: '!' },
    'Digit2': { label: '2', subLabel: '"' },
    'Digit3': { label: '3', subLabel: '#' },
    'Digit4': { label: '4', subLabel: '$' },
    'Digit5': { label: '5', subLabel: '%' },
    'Digit6': { label: '6', subLabel: '&' },
    'Digit7': { label: '7', subLabel: '/' },
    'Digit8': { label: '8', subLabel: '(' },
    'Digit9': { label: '9', subLabel: ')' },
    'Digit0': { label: '0', subLabel: '=' },
    'Minus': { label: '\'', subLabel: '?' },
    'Equal': { label: '«', subLabel: '»' },
    'KeyQ': { label: 'Q' },
    'KeyW': { label: 'W' },
    'KeyE': { label: 'E' },
    'KeyR': { label: 'R' },
    'KeyT': { label: 'T' },
    'KeyY': { label: 'Y' },
    'KeyU': { label: 'U' },
    'KeyI': { label: 'I' },
    'KeyO': { label: 'O' },
    'KeyP': { label: 'P' },
    'BracketLeft': { label: '+', subLabel: '*' },
    'BracketRight': { label: '´', subLabel: '`' },
    'Backslash': { label: '~', subLabel: '^' },
    'KeyA': { label: 'A' },
    'KeyS': { label: 'S' },
    'KeyD': { label: 'D' },
    'KeyF': { label: 'F' },
    'KeyG': { label: 'G' },
    'KeyH': { label: 'H' },
    'KeyJ': { label: 'J' },
    'KeyK': { label: 'K' },
    'KeyL': { label: 'L' },
    'Semicolon': { label: 'Ç', subLabel: '' },
    'Quote': { label: 'º', subLabel: 'ª' },
    'KeyZ': { label: 'Z' },
    'KeyX': { label: 'X' },
    'KeyC': { label: 'C' },
    'KeyV': { label: 'V' },
    'KeyB': { label: 'B' },
    'KeyN': { label: 'N' },
    'KeyM': { label: 'M' },
    'Comma': { label: ',', subLabel: ';' },
    'Period': { label: '.', subLabel: ':' },
    'Slash': { label: '-', subLabel: '_' }
  },

  // 9. Italian
  'Italian': {
    'Backquote': { label: '\\', subLabel: '|' },
    'Digit1': { label: '1', subLabel: '!' },
    'Digit2': { label: '2', subLabel: '"' },
    'Digit3': { label: '3', subLabel: '£' },
    'Digit4': { label: '4', subLabel: '$' },
    'Digit5': { label: '5', subLabel: '%' },
    'Digit6': { label: '6', subLabel: '&' },
    'Digit7': { label: '7', subLabel: '/' },
    'Digit8': { label: '8', subLabel: '(' },
    'Digit9': { label: '9', subLabel: ')' },
    'Digit0': { label: '0', subLabel: '=' },
    'Minus': { label: '\'', subLabel: '?' },
    'Equal': { label: 'ì', subLabel: '^' },
    'KeyQ': { label: 'Q' },
    'KeyW': { label: 'W' },
    'KeyE': { label: 'E' },
    'KeyR': { label: 'R' },
    'KeyT': { label: 'T' },
    'KeyY': { label: 'Y' },
    'KeyU': { label: 'U' },
    'KeyI': { label: 'I' },
    'KeyO': { label: 'O' },
    'KeyP': { label: 'P' },
    'BracketLeft': { label: 'è', subLabel: 'é' },
    'BracketRight': { label: '+', subLabel: '*' },
    'Backslash': { label: 'ù', subLabel: '§' },
    'KeyA': { label: 'A' },
    'KeyS': { label: 'S' },
    'KeyD': { label: 'D' },
    'KeyF': { label: 'F' },
    'KeyG': { label: 'G' },
    'KeyH': { label: 'H' },
    'KeyJ': { label: 'J' },
    'KeyK': { label: 'K' },
    'KeyL': { label: 'L' },
    'Semicolon': { label: 'ò', subLabel: 'ç' },
    'Quote': { label: 'à', subLabel: '°' },
    'KeyZ': { label: 'Z' },
    'KeyX': { label: 'X' },
    'KeyC': { label: 'C' },
    'KeyV': { label: 'V' },
    'KeyB': { label: 'B' },
    'KeyN': { label: 'N' },
    'KeyM': { label: 'M' },
    'Comma': { label: ',', subLabel: ';' },
    'Period': { label: '.', subLabel: ':' },
    'Slash': { label: '-', subLabel: '_' }
  },

  // 10. Turkish (Turkish Q)
  'Turkish': {
    'Backquote': { label: '"', subLabel: 'é' },
    'Digit1': { label: '1', subLabel: '!' },
    'Digit2': { label: '2', subLabel: '\'' },
    'Digit3': { label: '3', subLabel: '^' },
    'Digit4': { label: '4', subLabel: '+' },
    'Digit5': { label: '5', subLabel: '%' },
    'Digit6': { label: '6', subLabel: '&' },
    'Digit7': { label: '7', subLabel: '/' },
    'Digit8': { label: '8', subLabel: '(' },
    'Digit9': { label: '9', subLabel: ')' },
    'Digit0': { label: '0', subLabel: '=' },
    'Minus': { label: '*', subLabel: '?' },
    'Equal': { label: '-', subLabel: '_' },
    'KeyQ': { label: 'Q' },
    'KeyW': { label: 'W' },
    'KeyE': { label: 'E' },
    'KeyR': { label: 'R' },
    'KeyT': { label: 'T' },
    'KeyY': { label: 'Y' },
    'KeyU': { label: 'U' },
    'KeyI': { label: 'I', subLabel: 'ı' },
    'KeyO': { label: 'O' },
    'KeyP': { label: 'P' },
    'BracketLeft': { label: 'Ğ', subLabel: '' },
    'BracketRight': { label: 'Ü', subLabel: '' },
    'Backslash': { label: ',', subLabel: ';' },
    'KeyA': { label: 'A' },
    'KeyS': { label: 'S' },
    'KeyD': { label: 'D' },
    'KeyF': { label: 'F' },
    'KeyG': { label: 'G' },
    'KeyH': { label: 'H' },
    'KeyJ': { label: 'J' },
    'KeyK': { label: 'K' },
    'KeyL': { label: 'L' },
    'Semicolon': { label: 'Ş', subLabel: '' },
    'Quote': { label: 'İ', subLabel: '' },
    'KeyZ': { label: 'Z' },
    'KeyX': { label: 'X' },
    'KeyC': { label: 'C' },
    'KeyV': { label: 'V' },
    'KeyB': { label: 'B' },
    'KeyN': { label: 'N' },
    'KeyM': { label: 'M' },
    'Comma': { label: 'Ö', subLabel: '' },
    'Period': { label: 'Ç', subLabel: '' },
    'Slash': { label: '.', subLabel: ':' }
  },

  // 11. DVORAK
  'DVORAK': {
    'Backquote': { label: '`', subLabel: '~' },
    'Digit1': { label: '1', subLabel: '!' },
    'Digit2': { label: '2', subLabel: '@' },
    'Digit3': { label: '3', subLabel: '#' },
    'Digit4': { label: '4', subLabel: '$' },
    'Digit5': { label: '5', subLabel: '%' },
    'Digit6': { label: '6', subLabel: '^' },
    'Digit7': { label: '7', subLabel: '&' },
    'Digit8': { label: '8', subLabel: '*' },
    'Digit9': { label: '9', subLabel: '(' },
    'Digit0': { label: '0', subLabel: ')' },
    'Minus': { label: '[', subLabel: '{' },
    'Equal': { label: ']', subLabel: '}' },
    'KeyQ': { label: '\'', subLabel: '"' },
    'KeyW': { label: ',', subLabel: '<' },
    'KeyE': { label: '.', subLabel: '>' },
    'KeyR': { label: 'P' },
    'KeyT': { label: 'Y' },
    'KeyY': { label: 'F' },
    'KeyU': { label: 'G' },
    'KeyI': { label: 'C' },
    'KeyO': { label: 'R' },
    'KeyP': { label: 'L' },
    'BracketLeft': { label: '/', subLabel: '?' },
    'BracketRight': { label: '=', subLabel: '+' },
    'Backslash': { label: '\\', subLabel: '|' },
    'KeyA': { label: 'A' },
    'KeyS': { label: 'O' },
    'KeyD': { label: 'E' },
    'KeyF': { label: 'U' },
    'KeyG': { label: 'I' },
    'KeyH': { label: 'D' },
    'KeyJ': { label: 'H' },
    'KeyK': { label: 'T' },
    'KeyL': { label: 'N' },
    'Semicolon': { label: 'S' },
    'Quote': { label: '-', subLabel: '_' },
    'KeyZ': { label: ';' , subLabel: ':' },
    'KeyX': { label: 'Q' },
    'KeyC': { label: 'J' },
    'KeyV': { label: 'K' },
    'KeyB': { label: 'X' },
    'KeyN': { label: 'B' },
    'KeyM': { label: 'M' },
    'Comma': { label: 'W' },
    'Period': { label: 'V' },
    'Slash': { label: 'Z' }
  },

  // 12. Colemak
  'Colemak': {
    'Backquote': { label: '`', subLabel: '~' },
    'Digit1': { label: '1', subLabel: '!' },
    'Digit2': { label: '2', subLabel: '@' },
    'Digit3': { label: '3', subLabel: '#' },
    'Digit4': { label: '4', subLabel: '$' },
    'Digit5': { label: '5', subLabel: '%' },
    'Digit6': { label: '6', subLabel: '^' },
    'Digit7': { label: '7', subLabel: '&' },
    'Digit8': { label: '8', subLabel: '*' },
    'Digit9': { label: '9', subLabel: '(' },
    'Digit0': { label: '0', subLabel: ')' },
    'Minus': { label: '-', subLabel: '_' },
    'Equal': { label: '=', subLabel: '+' },
    'KeyQ': { label: 'Q' },
    'KeyW': { label: 'W' },
    'KeyE': { label: 'F' },
    'KeyR': { label: 'P' },
    'KeyT': { label: 'G' },
    'KeyY': { label: 'J' },
    'KeyU': { label: 'L' },
    'KeyI': { label: 'U' },
    'KeyO': { label: 'Y' },
    'KeyP': { label: ';' , subLabel: ':' },
    'BracketLeft': { label: '[', subLabel: '{' },
    'BracketRight': { label: ']', subLabel: '}' },
    'Backslash': { label: '\\', subLabel: '|' },
    'KeyA': { label: 'A' },
    'KeyS': { label: 'R' },
    'KeyD': { label: 'S' },
    'KeyF': { label: 'T' },
    'KeyG': { label: 'D' },
    'KeyH': { label: 'H' },
    'KeyJ': { label: 'N' },
    'KeyK': { label: 'E' },
    'KeyL': { label: 'I' },
    'Semicolon': { label: 'O' },
    'Quote': { label: '\'', subLabel: '"' },
    'KeyZ': { label: 'Z' },
    'KeyX': { label: 'X' },
    'KeyC': { label: 'C' },
    'KeyV': { label: 'V' },
    'KeyB': { label: 'B' },
    'KeyN': { label: 'K' },
    'KeyM': { label: 'M' },
    'Comma': { label: ',', subLabel: '<' },
    'Period': { label: '.', subLabel: '>' },
    'Slash': { label: '/', subLabel: '?' }
  }
};

export type FormFactor = 'ANSI' | 'ISO' | 'TKL' | '75%' | '65%' | '60%';

export interface KeyConfig {
  code: string;
  label: string;
  subLabel?: string;
  macLabel?: string;
  w: number; // width in units (1 = 1U, 1.25 = 1.25U, etc.)
  h?: number; // height in units (2 = 2U tall)
  isGap?: boolean;
  section?: 'function' | 'alpha' | 'nav' | 'arrows' | 'numpad';
}

export const GAMING_KEYS = new Set([
  'KeyW', 'KeyA', 'KeyS', 'KeyD',
  'ArrowUp', 'ArrowDown', 'ArrowLeft', 'ArrowRight',
  'Space', 'ShiftLeft', 'ShiftRight',
  'ControlLeft', 'AltLeft',
  'KeyQ', 'KeyE', 'KeyR', 'KeyF',
  'Digit1', 'Digit2', 'Digit3', 'Digit4', 'Digit5'
]);

export const NUMPAD_KEYS = new Set([
  'NumLock', 'NumpadDivide', 'NumpadMultiply', 'NumpadSubtract',
  'Numpad7', 'Numpad8', 'Numpad9', 'NumpadAdd',
  'Numpad4', 'Numpad5', 'Numpad6',
  'Numpad1', 'Numpad2', 'Numpad3', 'NumpadEnter',
  'Numpad0', 'NumpadDecimal'
]);

export const FUNCTION_KEYS = new Set([
  'Escape', 'F1', 'F2', 'F3', 'F4', 'F5', 'F6', 'F7', 'F8', 'F9', 'F10', 'F11', 'F12',
  'PrintScreen', 'ScrollLock', 'Pause'
]);

export const BROWSER_RESTRICTED_KEYS = new Set([
  'F1', 'F3', 'F5', 'F7', 'F11', 'F12',
  'MetaLeft', 'MetaRight', 'Tab', 'AltLeft', 'AltRight', 'ContextMenu'
]);

export const ROLLOVER_COMBOS = [
  { name: 'WASD + Space', keys: ['KeyW', 'KeyA', 'KeyS', 'KeyD', 'Space'] },
  { name: 'Shift + WASD', keys: ['ShiftLeft', 'KeyW', 'KeyA', 'KeyS', 'KeyD'] },
  { name: 'Ctrl + Shift + Space', keys: ['ControlLeft', 'ShiftLeft', 'Space'] },
  { name: 'Arrow Cluster (↑ ↓ ← →)', keys: ['ArrowUp', 'ArrowDown', 'ArrowLeft', 'ArrowRight'] },
  { name: 'QWER + Space', keys: ['KeyQ', 'KeyW', 'KeyE', 'KeyR', 'Space'] },
];
